### ISSUE TITLE
Training on KITTI Dataset

### ISSUE THREAD

**Issue by swords123** [xuelin-chen/pcl2pcl-gan-pub#1]
Hello, I want to train your network on KITTI Dataset, but I don't know how to get the data of ground truth of KITTI Dataset and the Complete 3D point cloud of cars, can you tell me how to get these data?

**Comment by xuelin-chen** [comment]
Hi, @pwllr, sorry for the late reply.
Unfortunately, the ground truth of the partial cars is not available in KITTI dataset.
