### ISSUE TITLE
can you provide your visualization scripts to render the point cloud? 

### ISSUE THREAD

**Issue by AmmonZ** [xuelin-chen/pcl2pcl-gan-pub#10]
Thank you for your great work! can you provide your visualization scripts to render the point cloud?

**Comment by xuelin-chen** [comment]
Hi @AmmonZ,

I found many people are so interested in the visualization code. But unfortunately, it was not simply done by a piece of code.

The only script I can provide is "pcl2pcl-gan-pub/pc2pc/tools/render_results/convert_point_cloud_to_balls.py", which I used to convert the raw point cloud to sphere meshes.
Then the final renderings were done in the 3rd party rendering software, with some code to automate the whole thing.

For the rendering software, Maya, 3D MAX and Keyshot can all do the job, just pick one that you are familiar with and automate the pipeline with a little piece of code. :)
