### ISSUE TITLE
Memory Requirement

### ISSUE THREAD

**Issue by azuki-miho** [xuelin-chen/pcl2pcl-gan-pub#12]
Because the data processing seems memory-consuming, can you tell me the memory used to process the data.

**Comment by xuelin-chen** [comment]
It is not clear to me which data processing you were referring to, and I probably have forgotten the specifics of the memory usage...
But just FYI, the server I was using has 128GB of memory, and the training will load all data of a specific category at the start, which, for the chair, is going to be 20-30GB.
Hope this somewhat helps a bit. ;-)

**Comment by azuki-miho** [comment]
Thanks for your response. Specifically, I mean the process to generate "*_rotated.pickle" files. Can you directly share these generated "*_rotated.pickle" files through the net disk?

**Comment by xuelin-chen** [comment]
The "*_rotated.pickle" will be generated at the start of the training on-the-fly, this means that the memory usage is probably going to be doubled. 
I found I did not save them out for sharing, so I am sorry that I am not able to share them directly.
