### ISSUE TITLE
About the dataset downloaded

### ISSUE THREAD

**Issue by qinglew** [xuelin-chen/pcl2pcl-gan-pub#13]
There are 10 files in the dataset you privided. I download all the files and try unzip command, but I got an error message:

```shell
error: invalid zip file with overlapped components (possible zip bomb)
```

How to solve this problem? The platform I used is Ubuntu 18.04 LTS.

**Comment by lx709** [comment]
Hello @qinglew, I met the same problem. Have you solved this problem?
