### ISSUE TITLE
How can I download your dataset?

### ISSUE THREAD

**Issue by NguyenTriTrinh** [xuelin-chen/pcl2pcl-gan-pub#2]
Hi，The dataset download method you provided has invalid link. How can I download your dataset?thanks a lot

**Comment by xuelin-chen** [comment]
Hi, @KEYZhongXiao , sorry for the late reply.
Just found this issue, however, the server holding the data has some issues that I am not able to fix.
Besides, the code and data have been changed a bit since the last submission, so the current repo is sort of outdated.
We will soon update this repo.
Thanks!

**Comment by Condor-G** [comment]
Could you plz share the data.zip on baidu cloud? 
It might be more convenient. (just I think)
thx~

**Comment by gtmtg** [comment]
@ChenXuelinCXL  Following up on this — I'm a student hoping to extend this work for a class project, but I need the dataset. Is there any chance you'd be able to post a link ASAP?

**Comment by xuelin-chen** [comment]
hi @gtmtg, sorry for the late reply. After another round of submission, We are planning on releasing the code for generating the point cloud data we used in the paper, as the data itself is too large. Unfortunately, I am traveling at the moment, I should be able to check the code and release it in 36 hours. Hope this works for you. :)

**Comment by gtmtg** [comment]
@ChenXuelinCXL  That's perfect, thank you so much! Safe travels :)

**Comment by xuelin-chen** [comment]
Hi, @NguyenTriTrinh @KEYZhongXiao @Condor-G  @gtmtg , I just cleaned and released the code for scanning to generate ShapeNet point cloud data. Please check out this repo: https://github.com/ChenXuelinCXL/blender_renderer

This repo is used in my latest project, although all virtual scanners should result in similar point clouds, just to let you guys know that the data used in the unpaired point cloud completion paper was NOT generated by it.

It was done in a rush, hope it works from your end. :)

**Comment by zcoo** [comment]
@ChenXuelinCXL Hi! I think the above repo is used for generate ShapeNet **Clean and Complete Point Sets**. Could you please share the **3D-EPN Dataset** which was provided by its author or **Synthetic Data Generation** for partial incomplete input training? 

Btw, what do you mean the data used  in paper was NOT generated by it? Do you mean for the random number used in generating, the point clouds have a little bit different or something else?
Thanks a lot.

**Comment by xuelin-chen** [comment]
Hi @zcoo , yes, the repo is for generating ShapeNet clean and complete point clouds, the class 'ShapeNetPartPointsDataset_V1' will take as input these point clouds and generate noisy and partial point clouds on-the-fly during the training.

We take the publicly available 3D-EPN dataset from their project page, please refer to their page for downloading.

"what do you mean the data used in paper was NOT generated by it?": we used another repo to scan the clean and complete point clouds, that repo is much more difficult to compile as it was done in c++ and needs many more c++ libraries. The blender python script is more user-friendly, hopefully so. This should not lead to very different results, as the dense scanned point clouds will be downsampled and resampled on-the-fly, giving us rather sparse point clouds (2k points), I believe the difference is neglectable. :)

**Comment by zcoo** [comment]
Thank you very much for your response!

**Comment by zcoo** [comment]
I am sorry to trouble u again! I wonder what is the difference between "virtual_scan_shapenet-v1_objects.py" and "blender_renderer/generate_shapenet_point_cloud.py". Are they doing the same things?

**Comment by xuelin-chen** [comment]
The virtual_scan_shapenet_v1_objects.py was previously used to generate the point cloud scans, it will call a scanner executable, which is written in c++ and needs PCL library to compile.
