### ISSUE TITLE
Cannot download the data.

### ISSUE THREAD

**Issue by diviswen** [xuelin-chen/pcl2pcl-gan-pub#3]
It seems like that the link for downloading the **data** points to a missing page.
Could you please provide an alternative way for download or fix that link. 
Thanks!

**Comment by xuelin-chen** [comment]
Hi @diviswen, sorry for late reply.
We no longer provide direct data download as it is too large, and instead, we release the code for the data generation.
Please check out the code here:
https://github.com/ChenXuelinCXL/blender_renderer
