### ISSUE TITLE
How do you use the EMD loss and Haussdroff Loss

### ISSUE THREAD

**Issue by prashkmr** [xuelin-chen/pcl2pcl-gan-pub#5]
Hi Chen,

The work in this paper is quite amazing seeing the results.
Can you shed some light on how you use the EMD and the Hausdorff distance to calculate the loss for the point clouds? Can you share some code for it that can be plugged in right away? 
Actually, we are implementing some network that can be greatly helped by your implemention.

If you can share the details and share the code for the EMD and Hausdorff distance, it would be of immense help to us.

Thanks,
Prashant

**Comment by xuelin-chen** [comment]
hi @prashant030591 , great to hear that our work can be helpful. Even though the current repo is out-dated, the code for the EMD and Hausdorff distance is ready for use. Please check out the code under pcl2pcl-gan-pub/pc2pc/structural_losses_utils/.

Thanks. :)
