### ISSUE TITLE
Could you provide the real scanned data?

### ISSUE THREAD

**Issue by XLechter** [xuelin-chen/pcl2pcl-gan-pub#6]
Hi, xuelin,
I am really interested in your work, and can you provide or give some suggestions about how your extract the partial object from Scannet?
Thanks!

**Comment by xuelin-chen** [comment]
hi, @XLechter , sorry for the late reply. 
The real partial scans were extracted from the Scannet using the instance labels and re-oriented manually to be consistently aligned, so we only managed to get around 550 objects for each class of chair and table.
The real data can now be found in the newly provided data download link.
