### ISSUE TITLE
data preprocessing code

### ISSUE THREAD

**Issue by xiazhiwang-zz** [xuelin-chen/pcl2pcl-gan-pub#8]
Thanks for your excellent work.
Could you please share the code for extracting and aligning objects for scannet dataset?

**Comment by xuelin-chen** [comment]
hi @xiazhiwang , I am sorry for not being able to provide that, as this data processing is not trivial and was done manually.

**Comment by xiazhiwang-zz** [comment]
@xuelin-chen can you roughly explain the object alignment process? Thanks.
