### ISSUE TITLE
AttributeError: module  'pymesh' has no attribute "Quaternion"

### ISSUE THREAD

**Issue by Katrina-cmd** [xuelin-chen/pcl2pcl-gan-pub#9]
Hi, Thank you for open sourcing the code. It's a good work.

When running the code, I went into a problem. I ran CUDA_VISIBLE_DEVICES=0 python3 train_ae_ShapeNet-v1.py and got an error.

> Traceback (most recent call last):
  File "train_ae_ShapeNet-v1.py", line 104, in <module>
    TRAIN_DATASET = shapenet_pc_dataset.ShapeNetPartPointsDataset_V1(para_config['point_cloud_dir'], batch_size=para_config['batch_size'], npoint=para_config['point_cloud_shape'][0], shuffle=True, split='trainval', preprocess=False)
  File "/home/user05/Shuyan/pcl2pcl-gan-pub/pc2pc/shapenet_pc_dataset.py", line 430, in __init__
    self.point_clouds = self._read_all_pointclouds(self.point_cloud_dir)
  File "/home/user05/Shuyan/pcl2pcl-gan-pub/pc2pc/shapenet_pc_dataset.py", line 477, in _read_all_pointclouds
    rotated_points = pc_util.rotate_point_cloud_by_axis_angle(pc, [0,1,0], 90)
  File "/home/user05/Shuyan/pcl2pcl-gan-pub/utils/pc_util.py", line 564, in rotate_point_cloud_by_axis_angle
    rot_m = pymesh.Quaternion.fromAxisAngle(axis, angle)
AttributeError: module 'pymesh' has no attribute 'Quaternion'

I want to know which version of pymesh you are using, or is your pymesh downloaded from GitHub?

**Comment by Condor-G** [comment]
Hello, I had the same problem.
try this method to install the pymesh library
`https://pymesh.readthedocs.io/en/latest/installation.html`

**Comment by Katrina-cmd** [comment]
@Condor-G 
Oh, thanks. I will give it a try.

**Comment by xuelin-chen** [comment]
I guess it may be caused by the pymesh of different versions, the api may be different in different versions.
Simply try to install the pymesh of different versions, see which one works. :)
